[tool.poetry]
name = "ejercicio-03"
version = "0.1.0"
description = ""
authors = ["Angel Moreno <anmoreno@gbm.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
